namespace SexFaces
{
    internal enum FBSIndex
    {
        Face,
        Neck,
        Teeth,
        Eyes,
        Tongue
    }

    internal enum EyebrowPattern
    {
        Default,
        Angry,
        Worried,
        Bored,
        DoubtL,
        DoubtR,
        ThinkingL,
        ThinkingR,
        FuriousL,
        FuriousR,
        Serious,
        Anxious,
        Surprised,
        Disappointed,
        Smug,
        WinkingL,
        WinkingR
    }

    internal enum EyePattern
    {
        Default,
        Closed,
        Smiling,
        HappyClosed,
        Happy,
        WinkingL,
        WinkingR,
        Pained,
        Bashful,
        Angry,
        Serious,
        Bored,
        Awkward,
        Hate,
        Thinking,
        Sad,
        Crying,
        Impatient,
        Disappointed,
        Worried,
        Smug
    }

    internal enum MouthPattern
    {
        Default,
        Smiling,
        HappyBroad,
        HappyModerate,
        HappySlight,
        ExcitedBroad,
        ExcitedModerate,
        ExcitedSlight,
        Angry,
        Angry2,
        Serious1,
        Serious2,
        Hate,
        Lonely,
        Impatient,
        Dissatisfied,
        Amazed,
        Surprised,
        SurprisedModerate,
        Smug,
        Playful,
        Eating,
        HoldInMouth,
        Kiss,
        TongueOut,
        SmallA,
        BigA,
        SmallI,
        BigI,
        SmallU,
        BigU,
        SmallE,
        BigE,
        SmallO,
        BigO,
        SmallN,
        BigN,
        Catlike,
        Triangle,
        CartoonySmile,
        Unknown1,
        Unknown2,
        Unknown3,
        Ahegao1,
        Ahegao2,
        Ahegao3,
        SneerL,
        SneerR,
        Smirk1L,
        Smirk1R,
        Smirk2L,
        Smirk2R
    }
}